language: node_js
node_js:
  - 10
stages:
  - lint
  - test
  - tweet
jobs:
  include:
    - stage: lint
      if: tag IS blank
      install: npm install standard
      script: npm run lint
    - stage: tweet
      if: type = cron
      install: npm i -g juicy-coupon-bot
      script: juicy-coupon-bot
notifications:
  slack:
    rooms:
      secure: CkJv/srViebermSM6E9dNFGDGaY5bwHhUqUfv02Mj2qUPOfpAILOoTbwoSmUnCOUeezXITPu5c6ImeNmmeKIDmoSqVuETS/jREvc6m4OvzBPHfWtcJ+myU6+avGXgMDOuq9+M+zj/5YjquUZ610qI3h8QARMXCccqAfaTzK1KMz2iU/mJ/08hxQc1Vx2avpC+Z9DZY9jUXL3Q/O0RTdYechWYrXUnPzBTQOC7vpLUyG7fscEOleub+Aw1XSO5qrOkw/dRX37dt3Cj5djIKzP9zPvJcG+XQ16nfiwk2yhUWYjZ7VaUS8ngADzgsGC9wi/4mltN3D1OKKbuhdApfby73vVJrCWnI42WESUsQqq80OV9ZFzt3fk5GVk3wa4NmmfF6+GDcuSTb48Ks93Dd2YtbxLU+UTnVTWfL7I0P8krUPgEv8IaMA7NOlp8d+TVASPqnXgK6Q+akwwnrmHhJMxtiG9gtBUBomMeyvtwilZ3CkbhUN/TPMwRZ6VkCL+JrjesGYGyhZgAjYZm5G0129sih3xehBcUsrr+SdWZwpNd9TNJHthVDbjM4g9DLPA26stPZUI8JcdK9M3TxbRHGPAk/6t+TFvo/kQmD4Lvtd3PVaUV4i89V40DzerJA2PNRD/V/dwARuItBaVNdYM83pp7YQVvcm/dtP+LY45nEh5/HU=
    on_success: change
    on_failure: change
    on_start: never
    on_pull_requests: false