name: "Monthly Coupon Distribution"
on:
  schedule:
    - cron:  '1 1 1 * *'
  push: # TODO Remove after successful testing!
    branches:
      - '*'
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v2
      - name: "Use Node.js 12"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "Install latest published module from NPM"
        run: npm i -g juicy-coupon-bot
      - name: "Activate publishing mode"
        run: |
          echo "TRAVIS_EVENT_TYPE=cron" >> $GITHUB_ENV
      - name: "Distribute coupons"
        run: juicy-coupon-bot
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
